
/*
 * Filename: sc_event_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Event signal for controlling our state machine
 */

#ifndef _H_DEFINE_SC_EVENT_TYPE
#define _H_DEFINE_SC_EVENT_TYPE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SC_EVENT_INCLUDES */

/* USER CODE END SC_EVENT_INCLUDES */



/**********************************************************************
 *       Type Definition for SC_EVENT signal    
 **********************************************************************/

/* USER CODE START SC_EVENT_USERDEFINITIONS */
typedef enum{
    EV_NONE,
    EV_KEYLEFT,
    EV_KEYRIGHT,
    EV_KEYRIGHTLONG,
    EV_1MIN,
    EV_250MS,
}EVENT_t;
/* USER CODE END SC_EVENT_USERDEFINITIONS */

typedef 
/* USER CODE START SC_EVENT_SIGNALDATADEFINITION */
struct
{
	EVENT_t ev;
} 
/* USER CODE END SC_EVENT_SIGNALDATADEFINITION */
SC_EVENT_data_t;

/* USER CODE START InitSC_EVENT */

#define SC_EVENT_INIT_DATA ((SC_EVENT_data_t){EV_NONE})
/* USER CODE END InitSC_EVENT */





/* USER CODE START SC_EVENT_USERFUNCTIONS */

/* USER CODE END SC_EVENT_USERFUNCTIONS */


#endif