
/*
 * Filename: sp_common.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Common PSOC Signal Pool
 */

#ifndef _H_DEFINE_SP_COMMON
#define _H_DEFINE_SP_COMMON

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SP_COMMON_INCLUDES */

/* USER CODE END SP_COMMON_INCLUDES */



#include "sc_event.h"
#include "sc_clock.h"
#include "sc_clock.h"



/*
 * description: An Event Signal for controlling state machine
 * indriver: 0
 * name: so_event
 * onDataError: 0
 * onDataUpdate: ev_event_onData
 * outdriver: 0
 * resource: None
 * shortname: event
 * signalclass: sc_event
 * signalpool: sp_common
 */
extern SC_EVENT_t SO_EVENT_signal;


/*
 * description: A Signal for our Electronic Clock
 * indriver: 0
 * name: so_clock
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: 0
 * resource: res_hmi
 * shortname: clock
 * signalclass: sc_clock
 * signalpool: sp_common
 */
extern SC_CLOCK_t SO_CLOCK_signal;


/*
 * description: Displaying to TFT
 * indriver: 0
 * name: so_display
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: res_hmi
 * shortname: display
 * signalclass: sc_clock
 * signalpool: sp_common
 */
extern SC_CLOCK_t SO_DISPLAY_signal;



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick);

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common();

#endif