/*
 * Filename: sc_breakpedal_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Signalclass for breakPedal(ISR button)
 * name: sc_breakPedal
 * shortname: breakPedal
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_breakpedal_type.h"



/* USER CODE START SC_BREAKPEDAL_INCLUDE */

/* USER CODE END SC_BREAKPEDAL_INCLUDE */




/* USER CODE START SC_BREAKPEDAL_USERDEFINITIONS */

/* USER CODE END SC_BREAKPEDAL_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_BREAKPEDAL signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_BREAKPEDAL_driverIn(SC_BREAKPEDAL_data_t *const data)
{
	/* USER CODE START driverInSC_BREAKPEDAL */
#error "Add your code here"

	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
	/* USER CODE END driverInSC_BREAKPEDAL */
}



