
/*
 * Filename: sp_common.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Common PSOC Signal Pool
 */

#ifndef _H_DEFINE_SP_COMMON
#define _H_DEFINE_SP_COMMON

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SP_COMMON_INCLUDES */

/* USER CODE END SP_COMMON_INCLUDES */



#include "sc_joystick.h"
#include "sc_speed.h"
#include "sc_engine.h"
#include "sc_breakpedal.h"
#include "sc_breaklight.h"
#include "sc_screen.h"



/*
 * description: Joystick input signal
 * indriver: default
 * name: so_joystick
 * onDataError: 0
 * onDataUpdate: ev_joystick_onData
 * outdriver: 0
 * resource: None
 * shortname: joystick
 * signalclass: sc_joystick
 * signalpool: sp_common
 */
extern SC_JOYSTICK_t SO_JOYSTICK_signal;


/*
 * description: Calculated speed signal
 * indriver: 0
 * name: so_speed
 * onDataError: 0
 * onDataUpdate: ev_speed_onData
 * outdriver: 0
 * resource: None
 * shortname: speed
 * signalclass: sc_speed
 * signalpool: sp_common
 */
extern SC_SPEED_t SO_SPEED_signal;


/*
 * description: A speed signal expored to hardware
 * indriver: 0
 * name: so_engine
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: engine
 * signalclass: sc_engine
 * signalpool: sp_common
 */
extern SC_ENGINE_t SO_ENGINE_signal;


/*
 * description: Break pedal signal object
 * indriver: default
 * name: so_breakPedal
 * onDataError: 0
 * onDataUpdate: ev_breakpedal_onData
 * outdriver: 0
 * resource: None
 * shortname: breakPedal
 * signalclass: sc_breakPedal
 * signalpool: sp_common
 */
extern SC_BREAKPEDAL_t SO_BREAKPEDAL_signal;


/*
 * description: A Signal
 * indriver: 0
 * name: so_breakLight
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: breakLight
 * signalclass: sc_breakLight
 * signalpool: sp_common
 */
extern SC_BREAKLIGHT_t SO_BREAKLIGHT_signal;


/*
 * description: A signal for displaying debugging task
 * indriver: 0
 * name: so_screen
 * onDataError: 0
 * onDataUpdate: ev_screen_onData
 * outdriver: default
 * resource: None
 * shortname: screen
 * signalclass: sc_screen
 * signalpool: sp_common
 */
extern SC_SCREEN_t SO_SCREEN_signal;



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick);

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common();

#endif