/*
 * Filename: tsk_hmi.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: HMI task
 * events: 
 * mode: Cyclic
 * name: tsk_hmi
 * shortname: hmi
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 10
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_hmi.h"



/* USER CODE START TSK_HMI_INCLUDE */

/* USER CODE END TSK_HMI_INCLUDE */

#include "swc_clock.h"



/* USER CODE START TSK_HMI_USERDEFINITIONS */

/* USER CODE END TSK_HMI_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Cyclic Table */

const RTE_cyclicTable_t RTE_cyclicActivationTable_tsk_hmi[] = {
	{ CLOCK_display_run, 250 },	//Runnable display on TFT
};
const uint16_t RTE_cyclicActivation_tsk_hmi_size = sizeof (RTE_cyclicActivationTable_tsk_hmi) / sizeof(RTE_cyclicTable_t); 


/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
 * description: HMI task
 * events: 
 * mode: Cyclic
 * name: tsk_hmi
 * shortname: hmi
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 10
 */
TASK(tsk_hmi)
{
	/* ticktime of the task */
	static uint32_t ticktime = 0;

	/* USER CODE START TSK_HMI_TASKBOBY_PRE */
    
	/* USER CODE END TSK_HMI_TASKBODY_PRE */
    
    //Process all cyclic runnables which are due
    RTE_ProcessCyclicTable(RTE_cyclicActivationTable_tsk_hmi, RTE_cyclicActivation_tsk_hmi_size, ticktime);
	
	/* USER CODE START TSK_HMI_TASKBODY_POST */
    
	/* USER CODE END TSK_HMI_TASKBODY_POST */

	ticktime += 10;
	if (ticktime > 0xFFFFFF00) ticktime = 0;
	
	TerminateTask();
    
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_HMI_ISR */

/* USER CODE END TSK_HMI_ISR */

