
/*
 * Filename: swc_gaspedal.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Gas Pedal Software Component
 */

#ifndef _H_DEFINE_SWC_GASPEDAL
#define _H_DEFINE_SWC_GASPEDAL

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SWC_GASPEDAL_INCLUDES */

/* USER CODE END SWC_GASPEDAL_INCLUDES */



/* USER CODE START SWC_GASPEDAL_USERDEFINITIONS */

/* USER CODE END SWC_GASPEDAL_USERDEFINITIONS */


/*
 * component: swc_GasPedal
 * cycletime: 10
 * description: Runnable
 * events: ev_10ms
 * name: GASPEDAL_readJoystick_run
 * shortname: readJoystick
 * signalIN: 
 * signalOUT: so_joystick
 * task: tsk_input
 */
void GASPEDAL_readJoystick_run(RTE_event ev);

/*
 * component: swc_GasPedal
 * cycletime: 100
 * description: Runnable
 * events: ev_onUpdate
 * name: GASPEDAL_calcControl_run
 * shortname: calcControl
 * signalIN: so_joystick
 * signalOUT: so_speed
 * task: tsk_control
 */
void GASPEDAL_calcControl_run(RTE_event ev);

/*
 * component: swc_GasPedal
 * cycletime: 100
 * description: Runnable
 * events: ev_100ms
 * name: GASPEDAL_setEngine_run
 * shortname: setEngine
 * signalIN: so_speed
 * signalOUT: 
 * task: tsk_control
 */
void GASPEDAL_setEngine_run(RTE_event ev);

/*
 * component: swc_GasPedal
 * cycletime: 100
 * description: Runnable
 * events: ev_onUpdate
 * name: GASPEDAL_setBrakeLight_run
 * shortname: setBrakeLight
 * signalIN: so_speed
 * signalOUT: 
 * task: tsk_control
 */
void GASPEDAL_setBrakeLight_run(RTE_event ev);


#endif