
/*
 * Filename: tsk_background.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Background task
 */

#ifndef _H_DEFINE_TSK_BACKGROUND
#define _H_DEFINE_TSK_BACKGROUND

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_BACKGROUND_INCLUDES */

/* USER CODE END TSK_BACKGROUND_INCLUDES */



/*
 * description: Background task
 * events: 
 * mode: Event
 * name: tsk_background
 * shortname: background
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 1
 */
DeclareTask(tsk_background);

/* USER CODE START TSK_BACKGROUND_TASKUSERFUNCTION */

/* USER CODE END TSK_BACKGROUND_TASKUSERFUNCTION */


#endif