
/*
 * Filename: tsk_init.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Initialization driver
 */

#ifndef _H_DEFINE_TSK_INIT
#define _H_DEFINE_TSK_INIT

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_INIT_INCLUDES */

/* USER CODE END TSK_INIT_INCLUDES */



/*
 * description: Initialization driver
 * events: 
 * mode: Event
 * name: tsk_init
 * shortname: init
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 1
 */
DeclareTask(tsk_init);

/* USER CODE START TSK_INIT_TASKUSERFUNCTION */

/* USER CODE END TSK_INIT_TASKUSERFUNCTION */


#endif