/*
 * Filename: tsk_input.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Task doing work
 * events: ev_10ms
 * mode: Cyclic
 * name: tsk_input
 * shortname: input
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_10ms
 * timertickperiod: 10
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_input.h"



/* USER CODE START TSK_INPUT_INCLUDE */

/* USER CODE END TSK_INPUT_INCLUDE */

#include "swc_gaspedal.h"



/* USER CODE START TSK_INPUT_USERDEFINITIONS */

/* USER CODE END TSK_INPUT_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Cyclic Table */

const RTE_cyclicTable_t RTE_cyclicActivationTable_tsk_input[] = {
	{ GASPEDAL_readJoystick_run, 10 },	//Runnable
};
const uint16_t RTE_cyclicActivation_tsk_input_size = sizeof (RTE_cyclicActivationTable_tsk_input) / sizeof(RTE_cyclicTable_t); 


/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
 * description: Task doing work
 * events: ev_10ms
 * mode: Cyclic
 * name: tsk_input
 * shortname: input
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_10ms
 * timertickperiod: 10
 */
TASK(tsk_input)
{
	/* ticktime of the task */
	static uint32_t ticktime = 0;

	/* USER CODE START TSK_INPUT_TASKBOBY_PRE */

	/* USER CODE END TSK_INPUT_TASKBODY_PRE */
    
    //Process all cyclic runnables which are due
    RTE_ProcessCyclicTable(RTE_cyclicActivationTable_tsk_input, RTE_cyclicActivation_tsk_input_size, ticktime);
	
	/* USER CODE START TSK_INPUT_TASKBODY_POST */

	/* USER CODE END TSK_INPUT_TASKBODY_POST */

	ticktime += 10;
	if (ticktime > 0xFFFFFF00) ticktime = 0;
	
	TerminateTask();
    
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_INPUT_ISR */

/* USER CODE END TSK_INPUT_ISR */

