/*
 * Filename: tsk_control.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Task doing work
 * events: ev_100ms|ev_10ms|ev_onUpdate
 * mode: Cyclic and Event
 * name: tsk_control
 * shortname: control
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_onUpdate
 * timertickperiod: 1
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_control.h"



/* USER CODE START TSK_CONTROL_INCLUDE */

/* USER CODE END TSK_CONTROL_INCLUDE */

#include "swc_gaspedal.h"



/* USER CODE START TSK_CONTROL_USERDEFINITIONS */

/* USER CODE END TSK_CONTROL_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Cyclic Table */

const RTE_cyclicTable_t RTE_cyclicActivationTable_tsk_control[] = {
	{ GASPEDAL_calcControl_run, 100 },	//Runnable
	{ GASPEDAL_setEngine_run, 100 },	//Runnable
	{ GASPEDAL_setBrakeLight_run, 100 },	//Runnable
};
const uint16_t RTE_cyclicActivation_tsk_control_size = sizeof (RTE_cyclicActivationTable_tsk_control) / sizeof(RTE_cyclicTable_t); 

/* Event Table */
const RTE_eventTable_t RTE_eventActivationTable_tsk_control[] = {
    { GASPEDAL_calcControl_run, ev_onUpdate },  //Runnable
    { GASPEDAL_setEngine_run, ev_100ms },  //Runnable
    { GASPEDAL_setBrakeLight_run, ev_onUpdate },  //Runnable
}; 
const uint16_t RTE_eventActivation_tsk_control_size = sizeof (RTE_eventActivationTable_tsk_control) / sizeof(RTE_eventTable_t);

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
 * description: Task doing work
 * events: ev_100ms|ev_10ms|ev_onUpdate
 * mode: Cyclic and Event
 * name: tsk_control
 * shortname: control
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_onUpdate
 * timertickperiod: 1
 */
TASK(tsk_control)
{
	/* ticktime of the task */
	uint32_t ticktime = 0;
	
    EventMaskType ev = 0;
	
	/* USER CODE START TSK_CONTROL_INIT */

	/* USER CODE END TSK_CONTROL_INIT */
    
    while(1)
    {
        //Wait, read and clear the event
        WaitEvent(ev_100ms|ev_10ms|ev_onUpdate);
        GetEvent(tsk_control,&ev);
        ClearEvent(ev);
    
		/* USER CODE START TSK_CONTROL_TASKBOBY_PRE */

		/* USER CODE END TSK_CONTROL_TASKBODY_PRE */
        
        if (ev & ev_onUpdate){
            //Process Cyclic table on tick
            RTE_ProcessCyclicTable(RTE_cyclicActivationTable_tsk_control, RTE_cyclicActivation_tsk_control_size, ticktime);

			ticktime += 1;
			if (ticktime > 0xFFFFFF00) ticktime = 0;

		};
		
		//Process data driven events
		RTE_ProcessEventTable(RTE_eventActivationTable_tsk_control, RTE_eventActivation_tsk_control_size, ev);
		
		/* USER CODE START TSK_CONTROL_TASKBODY_POST */

		/* USER CODE END TSK_CONTROL_TASKBODY_POST */
        
    }
	
	//Just in Case
	TerminateTask();
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_CONTROL_ISR */

/* USER CODE END TSK_CONTROL_ISR */

