/*
 * Filename: tsk_background.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Background task
 * events: 
 * mode: Event
 * name: tsk_background
 * shortname: background
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 1
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_background.h"



/* USER CODE START TSK_BACKGROUND_INCLUDE */

/* USER CODE END TSK_BACKGROUND_INCLUDE */




/* USER CODE START TSK_BACKGROUND_USERDEFINITIONS */

/* USER CODE END TSK_BACKGROUND_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Event Table */
const RTE_eventTable_t RTE_eventActivationTable_tsk_background[] = {
}; 
const uint16_t RTE_eventActivation_tsk_background_size = sizeof (RTE_eventActivationTable_tsk_background) / sizeof(RTE_eventTable_t);

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
 * description: Background task
 * events: 
 * mode: Event
 * name: tsk_background
 * shortname: background
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 1
 */
TASK(tsk_background)
{
    EventMaskType ev = 0;
    
	/* USER CODE START TSK_BACKGROUND_INIT */

	/* USER CODE END TSK_BACKGROUND_INIT */
	
    while(1)
    {
        //Wait, read and clear the event
        WaitEvent();
        GetEvent(tsk_background,&ev);
        ClearEvent(ev);
		
		/* USER CODE START TSK_BACKGROUND_TASKBOBY_PRE */

		/* USER CODE END TSK_BACKGROUND_TASKBODY_PRE */
    

        //Process Event table on event
        RTE_ProcessEventTable(RTE_eventActivationTable_tsk_background, RTE_eventActivation_tsk_background_size, ev);
		
		/* USER CODE START TSK_BACKGROUND_TASKBODY_POST */

		/* USER CODE END TSK_BACKGROUND_TASKBODY_POST */

        
    }
	
	//Just in Case
	TerminateTask();
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_BACKGROUND_ISR */

/* USER CODE END TSK_BACKGROUND_ISR */

