/*
 * Filename: swc_gaspedal.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Gas Pedal Software Component
 * name: swc_GasPedal
 * shortname: GasPedal
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_gaspedal.h"



/* USER CODE START SWC_GASPEDAL_INCLUDE */

/* USER CODE END SWC_GASPEDAL_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_GASPEDAL_USERDEFINITIONS */

/* USER CODE END SWC_GASPEDAL_USERDEFINITIONS */



/*
 * component: swc_GasPedal
 * cycletime: 10
 * description: Runnable
 * events: ev_10ms
 * name: GASPEDAL_readJoystick_run
 * shortname: readJoystick
 * signalIN: 
 * signalOUT: so_joystick
 * task: tsk_input
 */
void GASPEDAL_readJoystick_run(RTE_event ev){
	
	/* USER CODE START GASPEDAL_readJoystick_run */

    /* USER CODE END GASPEDAL_readJoystick_run */
}

/*
 * component: swc_GasPedal
 * cycletime: 100
 * description: Runnable
 * events: ev_onUpdate
 * name: GASPEDAL_calcControl_run
 * shortname: calcControl
 * signalIN: so_joystick
 * signalOUT: so_speed
 * task: tsk_control
 */
void GASPEDAL_calcControl_run(RTE_event ev){
	
	/* USER CODE START GASPEDAL_calcControl_run */

    /* USER CODE END GASPEDAL_calcControl_run */
}

/*
 * component: swc_GasPedal
 * cycletime: 100
 * description: Runnable
 * events: ev_100ms
 * name: GASPEDAL_setEngine_run
 * shortname: setEngine
 * signalIN: so_speed
 * signalOUT: 
 * task: tsk_control
 */
void GASPEDAL_setEngine_run(RTE_event ev){
	
	/* USER CODE START GASPEDAL_setEngine_run */

    /* USER CODE END GASPEDAL_setEngine_run */
}

/*
 * component: swc_GasPedal
 * cycletime: 100
 * description: Runnable
 * events: ev_onUpdate
 * name: GASPEDAL_setBrakeLight_run
 * shortname: setBrakeLight
 * signalIN: so_speed
 * signalOUT: 
 * task: tsk_control
 */
void GASPEDAL_setBrakeLight_run(RTE_event ev){
	
	/* USER CODE START GASPEDAL_setBrakeLight_run */

    /* USER CODE END GASPEDAL_setBrakeLight_run */
}

/* USER CODE START SWC_GASPEDAL_FUNCTIONS */

/* USER CODE END SWC_GASPEDAL_FUNCTIONS */

