
/*
 * Filename: tsk_tft.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: HMI task
 */

#ifndef _H_DEFINE_TSK_TFT
#define _H_DEFINE_TSK_TFT

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START TSK_TFT_INCLUDES */

/* USER CODE END TSK_TFT_INCLUDES */



/*
 * description: HMI task
 * events: ev_screen_onData
 * mode: Event
 * name: tsk_tft
 * shortname: tft
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 0
 */
DeclareTask(tsk_tft);

/* USER CODE START TSK_TFT_TASKUSERFUNCTION */

/* USER CODE END TSK_TFT_TASKUSERFUNCTION */


#endif