/*
 * Filename: tsk_tft.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: HMI task
 * events: ev_screen_onData
 * mode: Event
 * name: tsk_tft
 * shortname: tft
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 0
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_tft.h"



/* USER CODE START TSK_TFT_INCLUDE */

/* USER CODE END TSK_TFT_INCLUDE */

#include "swc_gaspedal.h"



/* USER CODE START TSK_TFT_USERDEFINITIONS */

/* USER CODE END TSK_TFT_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Event Table */
const RTE_eventTable_t RTE_eventActivationTable_tsk_tft[] = {
    { GASPEDAL_HMI_run, ev_screen_onData },  //Runnable
}; 
const uint16_t RTE_eventActivation_tsk_tft_size = sizeof (RTE_eventActivationTable_tsk_tft) / sizeof(RTE_eventTable_t);

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
 * description: HMI task
 * events: ev_screen_onData
 * mode: Event
 * name: tsk_tft
 * shortname: tft
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: 0
 * timertickperiod: 0
 */
TASK(tsk_tft)
{
    EventMaskType ev = 0;
    
	/* USER CODE START TSK_TFT_INIT */

	/* USER CODE END TSK_TFT_INIT */
	
    while(1)
    {
        //Wait, read and clear the event
        WaitEvent(ev_screen_onData);
        GetEvent(tsk_tft,&ev);
        ClearEvent(ev);
		
		/* USER CODE START TSK_TFT_TASKBOBY_PRE */

		/* USER CODE END TSK_TFT_TASKBODY_PRE */
    

        //Process Event table on event
        RTE_ProcessEventTable(RTE_eventActivationTable_tsk_tft, RTE_eventActivation_tsk_tft_size, ev);
		
		/* USER CODE START TSK_TFT_TASKBODY_POST */

		/* USER CODE END TSK_TFT_TASKBODY_POST */

        
    }
	
	//Just in Case
	TerminateTask();
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_TFT_ISR */

/* USER CODE END TSK_TFT_ISR */

