/*
 * Filename: sc_gaspedal_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Signalclass
 * name: sc_gaspedal
 * shortname: gaspedal
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_gaspedal_type.h"



/* USER CODE START SC_GASPEDAL_INCLUDE */

/* USER CODE END SC_GASPEDAL_INCLUDE */




/* USER CODE START SC_GASPEDAL_USERDEFINITIONS */

/* USER CODE END SC_GASPEDAL_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_GASPEDAL signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_GASPEDAL_driverIn(SC_GASPEDAL_data_t *const data)
{
	/* USER CODE START driverInSC_GASPEDAL */
#error "Add your code here"

	//Read data from the MCAL driver

	//Scale it to the application type

	return RC_SUCCESS;
	/* USER CODE END driverInSC_GASPEDAL */
}
/**
 * Default OUT driver API
 */
inline RC_t SC_GASPEDAL_driverOut(const SC_GASPEDAL_data_t  *const data)
{
	/* USER CODE START driverOutSC_GASPEDAL */
#error "Add your code here"

	//Scale application data to drive format

	//Write scaled data to driver

	return RC_SUCCESS;
	/* USER CODE END driverOutSC_GASPEDAL */
}



