
/*
 * Filename: sc_gaspedal_type.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: Signalclass
 */

#ifndef _H_DEFINE_SC_GASPEDAL_TYPE
#define _H_DEFINE_SC_GASPEDAL_TYPE

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SC_GASPEDAL_INCLUDES */

/* USER CODE END SC_GASPEDAL_INCLUDES */



/**********************************************************************
 *       Type Definition for SC_GASPEDAL signal    
 **********************************************************************/

/* USER CODE START SC_GASPEDAL_USERDEFINITIONS */

/* USER CODE END SC_GASPEDAL_USERDEFINITIONS */

typedef 
/* USER CODE START SC_GASPEDAL_SIGNALDATADEFINITION */
struct
{
	#error "Provide your data structure"
} 
/* USER CODE END SC_GASPEDAL_SIGNALDATADEFINITION */
SC_GASPEDAL_data_t;

/* USER CODE START InitSC_GASPEDAL */
#error "Provide a sensible init value"
#define SC_GASPEDAL_INIT_DATA ((SC_GASPEDAL_data_t){})
/* USER CODE END InitSC_GASPEDAL */


/**
 * Default IN driver API
 * \param SC_GASPEDAL_data_t *const data : [OUT] scaled data read from the driver
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t SC_GASPEDAL_driverIn(SC_GASPEDAL_data_t *const data);



/**
 * Default OUT driver API
 * \param const SC_GASPEDAL_data_t  *const data : [IN] signal data for the driver, will be scaled in this function
 * \return RC_SUCCESS is all was ok, error code otherwise
 */
RC_t SC_GASPEDAL_driverOut(const SC_GASPEDAL_data_t  *const data);


/* USER CODE START SC_GASPEDAL_USERFUNCTIONS */

/* USER CODE END SC_GASPEDAL_USERFUNCTIONS */


#endif