/*
 * Filename: sp_common.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: General PSOC signal
 * endaddr: 
 * name: sp_common
 * shortname: common
 * startaddr: 
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sp_common.h"



/* USER CODE START SP_COMMON_INCLUDE */

/* USER CODE END SP_COMMON_INCLUDE */

#include "sc_gaspedal.h"
#include "sc_gaspedal_type.h"
#include "sc_gaspedal.h"
#include "sc_gaspedal_type.h"



/* signal configuration */
/*
 * description: A Signal
 * indriver: default
 * name: so_joystick
 * onDataError: 0
 * onDataUpdate: ev_onUpdate
 * outdriver: default
 * resource: None
 * shortname: joystick
 * signalclass: sc_gaspedal
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_joystick_updTasks = { tsk_control };
 

static const SC_GASPEDAL_cfg_t SO_JOYSTICK_cfg = 
{
   /* indriver           */  SC_GASPEDAL_driverIn,
   /* outdriver          */  SC_GASPEDAL_driverOut,

   /* onUpdate           */  ev_onUpdate,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_joystick_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_joystick */


/* signal data */

SC_GASPEDAL_t SO_JOYSTICK_signal= 
{
   /* init value    */  SC_GASPEDAL_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_JOYSTICK_cfg,
}; /* data so_joystick */

/* signal configuration */
/*
 * description: Calculated speed signal
 * indriver: default
 * name: so_speed
 * onDataError: 0
 * onDataUpdate: ev_onUpdate
 * outdriver: default
 * resource: None
 * shortname: speed
 * signalclass: sc_gaspedal
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_speed_updTasks = { tsk_control };
 

static const SC_GASPEDAL_cfg_t SO_SPEED_cfg = 
{
   /* indriver           */  SC_GASPEDAL_driverIn,
   /* outdriver          */  SC_GASPEDAL_driverOut,

   /* onUpdate           */  ev_onUpdate,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_speed_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_speed */


/* signal data */

SC_GASPEDAL_t SO_SPEED_signal= 
{
   /* init value    */  SC_GASPEDAL_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_SPEED_cfg,
}; /* data so_speed */



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick){
   RTE_SC_GASPEDAL_incAge( &SO_JOYSTICK_signal, tick); 
   RTE_SC_GASPEDAL_incAge( &SO_SPEED_signal, tick); 
   
}

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common(){
   RTE_SC_GASPEDAL_init( &SO_JOYSTICK_signal); 
   RTE_SC_GASPEDAL_init( &SO_SPEED_signal); 
   
}		


