
/*
 * Filename: sp_common.h
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * Description: General PSOC signal
 */

#ifndef _H_DEFINE_SP_COMMON
#define _H_DEFINE_SP_COMMON

#include "project.h"
#include "global.h"
#include "rte_types.h"

/* USER CODE START SP_COMMON_INCLUDES */

/* USER CODE END SP_COMMON_INCLUDES */



#include "sc_gaspedal.h"
#include "sc_gaspedal.h"



/*
 * description: A Signal
 * indriver: default
 * name: so_joystick
 * onDataError: 0
 * onDataUpdate: ev_onUpdate
 * outdriver: default
 * resource: None
 * shortname: joystick
 * signalclass: sc_gaspedal
 * signalpool: sp_common
 */
extern SC_GASPEDAL_t SO_JOYSTICK_signal;


/*
 * description: Calculated speed signal
 * indriver: default
 * name: so_speed
 * onDataError: 0
 * onDataUpdate: ev_onUpdate
 * outdriver: default
 * resource: None
 * shortname: speed
 * signalclass: sc_gaspedal
 * signalpool: sp_common
 */
extern SC_GASPEDAL_t SO_SPEED_signal;



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick);

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common();

#endif