/*
 * Filename: sc_joystick_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Joystick signal class
 * name: sc_joystick
 * shortname: joystick
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_joystick_type.h"



/* USER CODE START SC_JOYSTICK_INCLUDE */

/* USER CODE END SC_JOYSTICK_INCLUDE */




/* USER CODE START SC_JOYSTICK_USERDEFINITIONS */

/* USER CODE END SC_JOYSTICK_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_JOYSTICK signal  ****************
 *****************************************************************************************/
 
 

/**
 * Default IN driver API
 */
inline RC_t SC_JOYSTICK_driverIn(SC_JOYSTICK_data_t *const data)
{
	/* USER CODE START driverInSC_JOYSTICK */
    sint8_t xHorizontal;
    sint8_t yVertical;

    
	//Read data from the MCAL driver
    RC_t result = JOYSTICK_ReadPosition(&xHorizontal, &yVertical);

    // voltage value / percentage value
    
	//Scale it to the application type
    data->xPos  = xHorizontal;
    
    //LOG_I("Xposition","%d",xHorizontal);
    
    data-> yPos = yVertical;
	return result;
	/* USER CODE END driverInSC_JOYSTICK */
}



