/*
 * Filename: sc_speed_type.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Speed signal class
 * name: sc_speed
 * shortname: speed
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sc_speed_type.h"



/* USER CODE START SC_SPEED_INCLUDE */

/* USER CODE END SC_SPEED_INCLUDE */




/* USER CODE START SC_SPEED_USERDEFINITIONS */

/* USER CODE END SC_SPEED_USERDEFINITIONS */


/*****************************************************************************************
 *************** Port Wrapper Implementation for SC_SPEED signal  ****************
 *****************************************************************************************/
 
 





