/*
 * Filename: sp_common.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Common PSOC Signal Pool
 * endaddr: ADR_SP_COMMON_END
 * name: sp_common
 * shortname: common
 * startaddr: ADR_SP_COMMON_START
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "sp_common.h"



/* USER CODE START SP_COMMON_INCLUDE */

/* USER CODE END SP_COMMON_INCLUDE */

#include "sc_joystick.h"
#include "sc_joystick_type.h"
#include "sc_speed.h"
#include "sc_speed_type.h"
#include "sc_engine.h"
#include "sc_engine_type.h"
#include "sc_breakpedal.h"
#include "sc_breakpedal_type.h"
#include "sc_breaklight.h"
#include "sc_breaklight_type.h"
#include "sc_screen.h"
#include "sc_screen_type.h"



/* signal configuration */
/*
 * description: Joystick input signal
 * indriver: default
 * name: so_joystick
 * onDataError: 0
 * onDataUpdate: ev_joystick_onData
 * outdriver: 0
 * resource: None
 * shortname: joystick
 * signalclass: sc_joystick
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_joystick_updTasks = { tsk_control };
 

static const SC_JOYSTICK_cfg_t SO_JOYSTICK_cfg = 
{
   /* indriver           */  SC_JOYSTICK_driverIn,
   /* outdriver          */  0,

   /* onUpdate           */  ev_joystick_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_joystick_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_joystick */


/* signal data */

SC_JOYSTICK_t SO_JOYSTICK_signal= 
{
   /* init value    */  SC_JOYSTICK_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_JOYSTICK_cfg,
}; /* data so_joystick */

/* signal configuration */
/*
 * description: Calculated speed signal
 * indriver: 0
 * name: so_speed
 * onDataError: 0
 * onDataUpdate: ev_speed_onData
 * outdriver: 0
 * resource: None
 * shortname: speed
 * signalclass: sc_speed
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_speed_updTasks = { tsk_io };
 

static const SC_SPEED_cfg_t SO_SPEED_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  0,

   /* onUpdate           */  ev_speed_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  1,
   /* task list onUpdate */  &so_speed_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_speed */


/* signal data */

SC_SPEED_t SO_SPEED_signal= 
{
   /* init value    */  SC_SPEED_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_SPEED_cfg,
}; /* data so_speed */

/* signal configuration */
/*
 * description: A speed signal expored to hardware
 * indriver: 0
 * name: so_engine
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: engine
 * signalclass: sc_engine
 * signalpool: sp_common
 */

 

static const SC_ENGINE_cfg_t SO_ENGINE_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  SC_ENGINE_driverOut,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_engine */


/* signal data */

SC_ENGINE_t SO_ENGINE_signal= 
{
   /* init value    */  SC_ENGINE_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_ENGINE_cfg,
}; /* data so_engine */

/* signal configuration */
/*
 * description: Break pedal signal object
 * indriver: default
 * name: so_breakPedal
 * onDataError: 0
 * onDataUpdate: ev_breakpedal_onData
 * outdriver: 0
 * resource: None
 * shortname: breakPedal
 * signalclass: sc_breakPedal
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_breakPedal_updTasks = { tsk_control, tsk_io };
 

static const SC_BREAKPEDAL_cfg_t SO_BREAKPEDAL_cfg = 
{
   /* indriver           */  SC_BREAKPEDAL_driverIn,
   /* outdriver          */  0,

   /* onUpdate           */  ev_breakpedal_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  2,
   /* task list onUpdate */  &so_breakPedal_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_breakpedal */


/* signal data */

SC_BREAKPEDAL_t SO_BREAKPEDAL_signal= 
{
   /* init value    */  SC_BREAKPEDAL_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_BREAKPEDAL_cfg,
}; /* data so_breakpedal */

/* signal configuration */
/*
 * description: A Signal
 * indriver: 0
 * name: so_breakLight
 * onDataError: 0
 * onDataUpdate: 0
 * outdriver: default
 * resource: None
 * shortname: breakLight
 * signalclass: sc_breakLight
 * signalpool: sp_common
 */

 

static const SC_BREAKLIGHT_cfg_t SO_BREAKLIGHT_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  SC_BREAKLIGHT_driverOut,

   /* onUpdate           */  0,
   /* onError            */  0,
   /* taskCount onUpdate */  0,
   /* task list onUpdate */  NULL,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_breaklight */


/* signal data */

SC_BREAKLIGHT_t SO_BREAKLIGHT_signal= 
{
   /* init value    */  SC_BREAKLIGHT_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_BREAKLIGHT_cfg,
}; /* data so_breaklight */

/* signal configuration */
/*
 * description: A signal for displaying debugging task
 * indriver: 0
 * name: so_screen
 * onDataError: 0
 * onDataUpdate: ev_screen_onData
 * outdriver: default
 * resource: None
 * shortname: screen
 * signalclass: sc_screen
 * signalpool: sp_common
 */


/* The following array contains the receiving tasks for onUpdate signal events */
const TaskTypeArray so_screen_updTasks = { tsk_control, tsk_tft };
 

static const SC_SCREEN_cfg_t SO_SCREEN_cfg = 
{
   /* indriver           */  0,
   /* outdriver          */  SC_SCREEN_driverOut,

   /* onUpdate           */  ev_screen_onData,
   /* onError            */  0,
   /* taskCount onUpdate */  2,
   /* task list onUpdate */  &so_screen_updTasks,
   /* taskCount onError  */  0,
   /* task list onError  */  NULL,

   /* resource active    */  FALSE,
   /* resource           */  0,
   
}; /* configuration so_screen */


/* signal data */

SC_SCREEN_t SO_SCREEN_signal= 
{
   /* init value    */  SC_SCREEN_INIT_DATA,
   /* status        */  RTE_SIGNALSTATUS_STARTUP,
   /* age           */  0,
   /* cfg           */  &SO_SCREEN_cfg,
}; /* data so_screen */



/*
 * Increments the age of the signals in this pool 
 */
void RTE_timertick_sp_common_tick(uint32_t tick){
   RTE_SC_JOYSTICK_incAge( &SO_JOYSTICK_signal, tick); 
   RTE_SC_SPEED_incAge( &SO_SPEED_signal, tick); 
   RTE_SC_ENGINE_incAge( &SO_ENGINE_signal, tick); 
   RTE_SC_BREAKPEDAL_incAge( &SO_BREAKPEDAL_signal, tick); 
   RTE_SC_BREAKLIGHT_incAge( &SO_BREAKLIGHT_signal, tick); 
   RTE_SC_SCREEN_incAge( &SO_SCREEN_signal, tick); 
   
}

/*
 * Reset all signals in this pool
 */
void RTE_reset_sp_common(){
   RTE_SC_JOYSTICK_init( &SO_JOYSTICK_signal); 
   RTE_SC_SPEED_init( &SO_SPEED_signal); 
   RTE_SC_ENGINE_init( &SO_ENGINE_signal); 
   RTE_SC_BREAKPEDAL_init( &SO_BREAKPEDAL_signal); 
   RTE_SC_BREAKLIGHT_init( &SO_BREAKLIGHT_signal); 
   RTE_SC_SCREEN_init( &SO_SCREEN_signal); 
   
}		


